apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: user-xmztt
    field.cattle.io/description: singlenodetest
  creationTimestamp: '2024-05-15T22:57:41Z'
  finalizers:
    - wrangler.cattle.io/cloud-config-secret-remover
    - wrangler.cattle.io/provisioning-cluster-remove
    - wrangler.cattle.io/rke-cluster-remove
  generation: 4
  managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/cloud-config-secret-remover": {}
        f:spec:
          f:rkeConfig:
            f:machinePoolDefaults: {}
      manager: rancher-v2.8.3-secret-migrator
      operation: Update
      time: '2024-05-15T22:57:41Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/description: {}
          f:finalizers:
            v:"wrangler.cattle.io/provisioning-cluster-remove": {}
            v:"wrangler.cattle.io/rke-cluster-remove": {}
        f:spec:
          .: {}
          f:cloudCredentialSecretName: {}
          f:defaultPodSecurityAdmissionConfigurationTemplateName: {}
          f:defaultPodSecurityPolicyTemplateName: {}
          f:kubernetesVersion: {}
          f:localClusterAuthEndpoint:
            .: {}
            f:caCerts: {}
            f:enabled: {}
            f:fqdn: {}
          f:rkeConfig:
            .: {}
            f:chartValues:
              .: {}
              f:rke2-cilium: {}
            f:etcd:
              .: {}
              f:disableSnapshots: {}
              f:snapshotRetention: {}
              f:snapshotScheduleCron: {}
            f:machineGlobalConfig:
              .: {}
              f:cni: {}
              f:disable-kube-proxy: {}
              f:etcd-expose-metrics: {}
            f:machinePools: {}
            f:machineSelectorConfig: {}
            f:registries:
              .: {}
              f:configs: {}
              f:mirrors: {}
            f:upgradeStrategy:
              .: {}
              f:controlPlaneConcurrency: {}
              f:controlPlaneDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
              f:workerConcurrency: {}
              f:workerDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
      manager: rancher
      operation: Update
      time: '2024-05-15T23:06:25Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:agentDeployed: {}
          f:clientSecretName: {}
          f:clusterName: {}
          f:conditions: {}
          f:fleetWorkspaceName: {}
          f:observedGeneration: {}
          f:ready: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2024-05-15T23:11:53Z'
  name: singlenodetest
  namespace: fleet-default
  resourceVersion: '11983697303'
  uid: 36bcc285-ad51-4d4a-af9c-ef36b3696a50
spec:
  cloudCredentialSecretName: cattle-global-data:cc-4nn46
  defaultPodSecurityAdmissionConfigurationTemplateName: ''
  defaultPodSecurityPolicyTemplateName: ''
  kubernetesVersion: v1.28.9+rke2r1
  localClusterAuthEndpoint:
    caCerts: ''
    enabled: false
    fqdn: ''
  rkeConfig:
    chartValues:
      rke2-cilium: {}
    etcd:
      disableSnapshots: false
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: cilium
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machinePoolDefaults: {}
    machinePools:
      - controlPlaneRole: true
        drainBeforeDelete: true
        dynamicSchemaSpec: >-
          {"resourceFields":{"accessKey":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Outscale
          Access
          Key"},"extraTagsAll":{"type":"array[string]","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"nullable":true,"create":true,"update":true,"description":"Tags
          to set at all created
          resources"},"extraTagsInstances":{"type":"array[string]","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"nullable":true,"create":true,"update":true,"description":"Tags
          to set only to instances
          \u003ckey1=value1,key2=value2\u003e"},"instanceType":{"type":"string","default":{"stringValue":"tinav6.c4r8p1","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"VM
          Instance
          type"},"kubernetesNodeNameAutotag":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Automatically
          add kubernetes tag 'OscK8sNodeName' to the instance (Useful for the
          CCM)"},"region":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Outscale
          Region (e.g.
          eu-west-2)"},"rootDiskIops":{"type":"string","default":{"stringValue":"1500","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Iops
          for the io1 root disk type (ignore if it is not io1). Value between 1
          and
          13000."},"rootDiskSize":{"type":"string","default":{"stringValue":"15","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Size
          of the root disk in GB (\u003e
          0)"},"rootDiskType":{"type":"string","default":{"stringValue":"gp2","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Type
          of volume for the root disk ('standard', 'io1' or
          'gp2')"},"secretKey":{"type":"password","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Outscale
          Secret
          Key"},"securityGroupIds":{"type":"array[string]","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"nullable":true,"create":true,"update":true,"description":"Add
          machine into theses security
          groups"},"sourceOmi":{"type":"string","default":{"stringValue":"ami-cd8d714e","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"OMI
          to use as
          bootstrap"},"subnetId":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Id
          of the Net use to create all resources when a private network is
          requested"},"userDataFile":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Path
          to cloud-init user-data file"}}}
        etcdRole: true
        machineConfigRef:
          kind: OutscaleConfig
          name: nc-singlenodetest-masteraorkerpool-kkkqb
        name: masteraorkerpool
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    registries:
      configs: {}
      mirrors: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
status:
  agentDeployed: true
  clientSecretName: singlenodetest-kubeconfig
  clusterName: c-m-chzpn7mr
  conditions:
    - lastUpdateTime: '2024-05-15T23:11:36Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2024-05-15T22:57:41Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2024-05-15T23:11:37Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2024-05-15T23:11:53Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2024-05-15T22:57:41Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2024-05-15T22:57:42Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2024-05-15T22:57:42Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2024-05-15T22:57:42Z'
      status: 'True'
      type: InitialRolesPopulated
    - lastUpdateTime: '2024-05-15T23:11:53Z'
      status: 'True'
      type: Updated
    - lastUpdateTime: '2024-05-15T23:11:53Z'
      status: 'True'
      type: Provisioned
    - lastUpdateTime: '2024-05-15T23:11:53Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2024-05-15T22:57:43Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2024-05-15T22:57:45Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2024-05-15T22:57:45Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2024-05-15T22:57:45Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2024-05-15T22:57:45Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2024-05-15T22:57:45Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2024-05-15T22:57:45Z'
      status: 'True'
      type: ACISecretsMigrated
    - lastUpdateTime: '2024-05-15T23:11:34Z'
      status: 'True'
      type: Connected
    - lastUpdateTime: '2024-05-15T23:11:06Z'
      status: 'True'
      type: GlobalAdminsSynced
    - lastUpdateTime: '2024-05-15T23:11:16Z'
      status: 'True'
      type: SystemAccountCreated
    - lastUpdateTime: '2024-05-15T23:11:21Z'
      status: 'True'
      type: AgentDeployed
    - lastUpdateTime: '2024-05-15T23:11:36Z'
      status: 'True'
      type: Waiting
  fleetWorkspaceName: fleet-default
  observedGeneration: 4
  ready: true
