{{- if eq .Values.cloudprovider "outscale" }}
{{- range $index, $nodepool := .Values.nodepools }}
apiVersion: rke-machine-config.cattle.io/v1
kind: OutscaleConfig
metadata:
  name: {{ $nodepool.name }}
  namespace: fleet-default
{{- if $nodepool.sourceOmi }}
sourceOmi: {{ $nodepool.sourceOmi }}
{{- end }}
# {{- if $nodepool.rootDiskSize }}
# rootDiskSize: {{ printf "\"%s\"" $nodepool.rootDiskSize }}
# {{- end }}
rootDiskSize: "20"
region: null
rootDiskIops: "1500"
rootDiskType: gp2
secretKey: null
securityGroupIds: []
{{- if $nodepool.subnetId }}
subnetId: {{ $nodepool.subnetId }}
{{- end }}
{{- end }}
{{- end }}