apiVersion: v1
name: outscale cluster-template
description: Cluster template for outscale rke2
version: 0.0.3
annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default
